### PR TITLE
Add link to bigger NSFW URLs dataset in README.md

### PR DESCRIPTION
**Pull request by EBazarov**
Link to this repository will help people to get bigger list of urls from which they can download NSFW content, that will give them more data and possibility to build robust NSFW classifier.

### CODE REVIEW

**Comment by orsinium** [comment]
Why don't you just contribute new lists here instead of creating new repo? It's OSS.

**Comment by EBazarov** [comment]
Because this repo contains good separation between categories pron | sexy | hentai | etc... and my source_urls provide just **raw** source of URLs and it's up to you in which categories to split them. Also even if I will push URLs as a new class, let's say NSFW class it will bring huge disbalance to dataset and you will never see such confusion matrix as you can see currently in this repository.

**Comment by alex000kim** [comment]
I don't want to confuse the users about the usage of the scripts, sorry. Closing the PR.

**Comment by orsinium** [comment]
@EBazrov, make sense. However, you can just put these 2 ways to categorize NSFW content into separated dirs like this:
```
5_cats
    hentai
    drawing
   ...
56_cats (or how many of them?)
    age
        college
        milf
       ...
   ...
```

You know, it's pretty cool to have all related stuff in the one place. For example, [SecLists](https://github.com/danielmiessler/SecLists) makes it.

**Pull request closed without merging**
